# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get Build Start Current Time
      uses: 1466587594/get-current-time@v2
      id: build-start-time
      with:
        format: YYYYMMDD-HH
        utcOffset: "+09:00" #한국 시간에 맞추기
    - name: Build Start Current Time
      env:
        TIME: "${{ steps.build-start-time.outputs.time }}"
        R_TIME: "${{ steps.build-start-time.outputs.readableTime }}"
        F_TIME: "${{ steps.build-start-time.outputs.formattedTime }}"
        YEAR: "${{ steps.build-start-time.outputs.year }}"
        DAY: "${{ steps.build-start-time.outputs.day }}"
      run: echo Build Start Time $TIME $R_TIME $F_TIME $YEAR $DAY
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Get Build End Current Time
      uses: 1466587594/get-current-time@v2
      id: build-end-time
      with:
        format: YYYYMMDD-HH
        utcOffset: "+09:00" #한국 시간에 맞추기
    - name: Use current time
      env:
        TIME: "${{ steps.build-end-time.outputs.time }}"
        R_TIME: "${{ steps.build-end-time.outputs.readableTime }}"
        F_TIME: "${{ steps.build-end-time.outputs.formattedTime }}"
        YEAR: "${{ steps.build-end-time.outputs.year }}"
        DAY: "${{ steps.build-end-time.outputs.day }}"
      run: echo Build End Time $TIME $R_TIME $F_TIME $YEAR $DAY